### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by yunhuige** [vvoelz/biceps#84]
Below is a verified steps to install the current BICePs version (2.0b0):
```
conda create -n biceps python=3.7
conda activate biceps
conda install numpy
conda install -c conda-forge mdtraj==1.9.3
pip install pymbar==3.0.2
pip install -i https://pypi.anaconda.org/rraddi/simple biceps
```

**Comment by robraddi** [comment]
I may have fixed some dependency issues noted above.  Unfortunately, `mdtraj` may need to be preinstalled. 
Install from pip 
 ```bash
  $ conda install -c conda-forge mdtraj  
  $ pip install biceps                   
```
Install from conda 
```bash
  $ conda create -n biceps python=3.7    
  $ conda activate biceps                
  $ conda install -c rraddi biceps      # -c will be conda-forge in future
```

**Comment by robraddi** [comment]
Use built-in GitHub Actions to **build across multiple operating systems and run tests** [(CI/CD)](https://github.com/marketplace?category=continuous-integration&type=actions). In addition, the link for these package releases on GitHub can be used as the main source for package managers like pip and conda when uploading the package. 

Below is the start of a continuous integration yaml file `biceps/.github/workflows/ci.yaml`

```
jobs:
   build:
      strategy:
         matrix:
            os:
               - macOS-latest
               - ubuntu-latest
               - windos-latest
...
```

Here's an [example](https://github.com/scipy/scipy/tree/master/.github/ISSUE_TEMPLATE) of an **issue template** used by `SciPy`.
